export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHANGE_PASS = 'AUTH_CHANGE_PASS';
export const AUTH_GET_PERMISSIONS = 'AUTH_GET_PERMISSIONS';
export const AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD';
export const AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD' ;