export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const ACTION_SAVE_REFRESH_TOKEN = 'app/saveRefreshToken';

export const ACTION_REMOVE_IDENTITY = 'ACTION_REMOVE_IDENTITY';
export const ACTION_LOGIN = 'ACTION_LOGIN';
export const ACTION_LOGOUT = 'ACTION_LOGOUT';
export const ACTION_UPDATE_TOKENS = 'ACTION_UPDATE_TOKENS';
export const ACTION_LOAD_IDENTITY = 'ACTION_LOAD_IDENTITY';
export const ACTION_UPDATE_IDENTITY = 'ACTION_UPDATE_IDENTITY';
export const ACTION_SAVE_PERMISSION = 'ACTION_SAVE_PERMISSION';
export const ACTION_GET_PERMISSION = 'ACTION_GET_PERMISSION';
export const ACTION_EDIT_IDENTITY = 'ACTION_EDIT_IDENTITY';
export const ACTION_CHANGE_PASSWORD = "ACTION_CHANGE_PASSWORD"