'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var AUTH_LOGIN = exports.AUTH_LOGIN = 'AUTH_LOGIN';
var AUTH_CHECK = exports.AUTH_CHECK = 'AUTH_CHECK';
var AUTH_ERROR = exports.AUTH_ERROR = 'AUTH_ERROR';
var AUTH_LOGOUT = exports.AUTH_LOGOUT = 'AUTH_LOGOUT';
var AUTH_CHANGE_PASS = exports.AUTH_CHANGE_PASS = 'AUTH_CHANGE_PASS';
var AUTH_GET_PERMISSIONS = exports.AUTH_GET_PERMISSIONS = 'AUTH_GET_PERMISSIONS';
var AUTH_FORGOT_PASSWORD = exports.AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD';
var AUTH_RESET_PASSWORD = exports.AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD';